version: '3.9'

services:
  aetherarchives-core-database:
    image: postgres:16
    container_name: core-database
    restart: on-failure
    ports:
      - '6968:5432'
    env_file:
      - ./backend/core/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - aetherarchives-network

  aetherarchives-minio:
    image: minio/minio:RELEASE.2024-07-29T22-14-52Z
    container_name: aetherarchives-minio
    command: server --console-address ":9001" /data/
    env_file:
      - ./backend/core/.env
    volumes:
      - minio_data:/data
    ports:
      - "9999:9000"
      - "9009:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - aetherarchives-network

  aetherarchives-core-server:
    build:
      context: ./backend/core
      dockerfile: ./Dockerfile
      target: dev
    container_name: core-server
    command: sh -c "./entrypoint.sh"
    restart: on-failure
    ports:
      - '6969:6969'
    env_file:
      - ./backend/core/.env
    volumes:
      - ./backend/core/src:/app/core/src
      - ./backend/core/config:/app/core/config
    depends_on:
      - aetherarchives-core-database
      - aetherarchives-minio
    networks:
      - aetherarchives-network

volumes:
  pg_data:
  minio_data:

networks:
  aetherarchives-network:
    driver: bridge
